// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductMicroservices.Context;

namespace ProductMicroservices.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20220629161427_secondMigration")]
    partial class secondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductMicroservices.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "APPLE iPhone 13 pro Max(Graphite 128 GB)",
                            Image_Name = "Iphone.jpg",
                            Name = "iPhone 13 Pro Max",
                            Price = 129999.0,
                            Rating = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "Brass Diamond bracelet with crystal clear finish",
                            Image_Name = "bracelet.jpg",
                            Name = "Brass Diamond Bracelet",
                            Price = 2490.0,
                            Rating = 3
                        },
                        new
                        {
                            Id = 3,
                            Description = "Men Slim Fit check slim collar casual shirt",
                            Image_Name = "shirt.jpg",
                            Name = "Shirt",
                            Price = 999.0,
                            Rating = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Blue Star Comvertible 4-in-1 Cooling 1.5 Ton 5 Star AC",
                            Image_Name = "ac.jpg",
                            Name = "Blue Star Inverter AC",
                            Price = 20999.0,
                            Rating = 3
                        },
                        new
                        {
                            Id = 5,
                            Description = "SAMSUNG 192L Direct Cool Single Door 2 Star Refrigerator",
                            Image_Name = "refri.jpg",
                            Name = "SAMSUNG Refrigerator",
                            Price = 13190.0,
                            Rating = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
